# Generated by Django 6.1.1 on 2026-10-02 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('toner', 'Toner'), ('residuo', 'Caixa de resíduo')], max_length=10)),
                ('estoque_unidade', models.PositiveIntegerField(default=0)),
                ('estoque_minimo', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloImpressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('caixa_residuo', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'residuo'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estoque.consumivel')),
                ('toner', models.ForeignKey(limit_choices_to={'tipo': 'toner'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estoque.consumivel')),
            ],
        ),
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('localizacao', models.CharField(max_length=150)),
                ('nivel_toner', models.PositiveIntegerField(default=100)),
                ('toner_na_sala', models.PositiveIntegerField(default=0)),
                ('residuo_na_sala', models.PositiveIntegerField(default=0)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.modeloimpressora')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('recebido', 'Recebido')], default='pendente', max_length=10)),
                ('solicitante', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consumivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.consumivel')),
            ],
        ),
    ]
