# Generated by Django 6.1.1 on 2026-10-02 14:58

import django.db.models.deletion
from django.db import migrations, models


def copiar_para_preto(apps, schema_editor):
    """Dados antigos tinham um toner único por modelo: viram a cor preta."""
    ModeloImpressora = apps.get_model('estoque', 'ModeloImpressora')
    Impressora = apps.get_model('estoque', 'Impressora')
    ModeloToner = apps.get_model('estoque', 'ModeloToner')
    NivelToner = apps.get_model('estoque', 'NivelToner')
    for modelo in ModeloImpressora.objects.all():
        ModeloToner.objects.create(modelo=modelo, cor='preto', consumivel_id=modelo.toner_id)
    for imp in Impressora.objects.all():
        NivelToner.objects.create(impressora=imp, cor='preto',
                                  nivel=imp.nivel_toner, na_sala=imp.toner_na_sala)


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloToner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(choices=[('preto', 'Preto'), ('ciano', 'Ciano (azul)'), ('magenta', 'Magenta'), ('amarelo', 'Amarelo')], max_length=10)),
                ('consumivel', models.ForeignKey(limit_choices_to={'tipo': 'toner'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estoque.consumivel')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toners', to='estoque.modeloimpressora')),
            ],
            options={
                'verbose_name': 'toner do modelo',
                'verbose_name_plural': 'toners do modelo',
                'constraints': [models.UniqueConstraint(fields=('modelo', 'cor'), name='modelo_cor_unica')],
            },
        ),
        migrations.CreateModel(
            name='NivelToner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(choices=[('preto', 'Preto'), ('ciano', 'Ciano (azul)'), ('magenta', 'Magenta'), ('amarelo', 'Amarelo')], max_length=10)),
                ('nivel', models.PositiveIntegerField(default=100)),
                ('na_sala', models.PositiveIntegerField(default=0)),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveis', to='estoque.impressora')),
            ],
            options={
                'verbose_name': 'nível de toner',
                'verbose_name_plural': 'níveis de toner',
                'constraints': [models.UniqueConstraint(fields=('impressora', 'cor'), name='impressora_cor_unica')],
            },
        ),
        migrations.RunPython(copiar_para_preto, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='impressora',
            name='nivel_toner',
        ),
        migrations.RemoveField(
            model_name='impressora',
            name='toner_na_sala',
        ),
        migrations.RemoveField(
            model_name='modeloimpressora',
            name='toner',
        ),
    ]
