# Generated by Django 6.1.1 on 2026-10-03 10:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_ajuste_de_reserva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_nome', models.CharField(max_length=100)),
                ('anterior', models.PositiveIntegerField()),
                ('novo', models.PositiveIntegerField()),
                ('usuario_nome', models.CharField(blank=True, max_length=150)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ajuste de estoque',
                'verbose_name_plural': 'ajustes de estoque',
                'ordering': ['-registrado_em', '-id'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='finalizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='finalizado_por',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='niveltoner',
            name='nivel',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], default='pendente', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='niveltoner',
            constraint=models.CheckConstraint(condition=models.Q(('nivel__lte', 100)), name='nivel_ate_100'),
        ),
        migrations.AddField(
            model_name='ajusteestoque',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes', to='estoque.consumivel'),
        ),
        migrations.AddField(
            model_name='ajusteestoque',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
