# Generated by Django 6.1.1 on 2026-10-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_cancelar_pedido_e_ajuste_de_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteestoque',
            name='motivo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
